name: propriocepce.cz
favicon: null
layout_spectrum: 0.5315942976158112
typography_spectrum: 0.8565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e00000'
    - '#000000'
    - '#ffffff'
    - '#fffefe'
    - '#fffdfd'
  brandStrength: 0.8355957928579301
  lightness: 0.8940466719213873
  saturation: 0.5
  rhythmicContrast: 0.632160265929997
purpose: []
